[PG-41] Listar editais na homepage
mate85-equipe03/frontend pull request #29
Opened 2022-09-18 15:04 UTC by mblucs

2022-09-18 17:08 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +      direction="column"
:eyes::eyes:

2022-09-18 17:10 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +            {editais.em_andamento.map((edital) => (
cadê a tipagem? rs

2022-09-18 17:10 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +            {editais.encerrados.map((edital) => (
tipagem rs

2022-09-18 17:13 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +      &nbsp;
```suggestion
      &nbsp;
```
??

2022-09-18 17:14 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +        nome: "Edital PGCOMP-03/2022",
faltou o "inscrito" dos encerrados

2022-09-18 17:15 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +          nome: "Divulgação dos Resultados Parciais",
```suggestion
          nome: "Divulgação dos Resultados Parciais",
```
Isso seria uma etapa?

2022-09-18 17:18 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +  const editais = {
Sugestão: Criar mock de acordo com a chave `user`. Se tiver `user`, fica como tá. Se `user` for `falsy`, fica sem a chave `inscritos`.

2022-09-18 17:32 UTC, mblucs commented on src/Components/Home.tsx
> +          nome: "Divulgação dos Resultados Parciais",
Sim, antes do recurso. Coloquei só pra dar exemplo de outra etapa. Tem um exemplo aqui https://pgcomp.ufba.br/edital-pgcomp-032022-processo-seletivo-para-concessao-de-bolsas-de-mestrado-e-doutorado-0

2022-09-18 17:32 UTC, mblucs commented on src/Components/Home.tsx
> +        nome: "Edital PGCOMP-03/2022",
ficaria com a msm mensagem? "vc está inscrito"?
pq na vdd foi no passado ne sla

2022-09-18 17:33 UTC, mblucs commented on src/Components/Home.tsx
> +      direction="column"
foi pro botão de login ficar embaixo. tu ve algum problema?

2022-09-18 17:33 UTC, mblucs commented on src/Components/Home.tsx
> +      &nbsp;
só pra dar um espaço entre o botão e o card. tava feio tudo juntoooooo

2022-09-18 17:39 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +        nome: "Edital PGCOMP-03/2022",
Eu colocaria sim. Pq mesmo que esteja encerrado, o usuário pode querer ter uma visão retroativa dos editais em que ele se inscreveu ou não, né?

2022-09-18 17:39 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +        nome: "Edital PGCOMP-03/2022",
A mensagem pode ser um "Você se inscreveu", sei lá kkkk

2022-09-18 17:40 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +      direction="column"
Aaaah, tranquilo

2022-09-18 17:40 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +      &nbsp;
KKKKKKKK
Padding, margin, gap...
Confio em vc kkkk

2022-09-19 01:13 UTC, BeatrizCerqueira requested changes

2022-09-19 01:13 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +        etapa: { nome: "Inscrições abertas", data_fim: "15/10/2021" },
```suggestion
        etapa: { nome: "Inscrições abertas", data_fim: "15/10/2022" },
```

2022-09-19 01:13 UTC, BeatrizCerqueira commented on src/Components/Home.tsx
> +        nome: "Edital PGCOMP-09/2022",
```suggestion
        nome: "Edital PGCOMP-09/2021",
```

2022-09-19 01:16 UTC, BeatrizCerqueira approved these changes

2022-09-19 01:25 UTC, BeatrizCerqueira approved these changes

2022-09-19 01:48 UTC, merged