POSG81 cadastro
mate85-equipe03/frontend pull request #44
Opened 2022-10-03 16:39 UTC by mblucs

Integração serviço

Validações dos inputs por tipo

Correções solicitadas pelo prof em sala

2022-10-06 22:26 UTC, BeatrizCerqueira requested changes

2022-10-06 23:07 UTC, mblucs commented on src/pages/Cadastro.tsx
> +  semestre_pgcomp: number | string;
no back ta assim

2022-10-06 23:14 UTC, mblucs commented on src/pages/Cadastro.tsx
> +      matricula: signUpData.login,
acho q o back vai deixar com uma só. eu particularmente acharia melhor

2022-10-06 23:14 UTC, mblucs commented on src/pages/Cadastro.tsx
> +  const [signUpSuccess, setSignUpSuccess] = React.useState<boolean | null>(
pra situação de n ter sido validado ainda, ai n mostra nem mensagem de erro nem de sucesso

2022-10-06 23:14 UTC, mblucs commented on src/pages/Cadastro.tsx
> +      .post("/alunos", signUpData)
sim, como coloca?

2022-10-06 23:14 UTC, mblucs commented on src/pages/Cadastro.tsx
> +    window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
a mensagem de sucesso ou erro ta no topo da tela.
isso é pra subir a tela pra ver a mensagem e saber se o cadastro foi realizado ou n.

Inicialmente tinha pensado em deixar essa mensagem na tela de login e redirecionar pra lá, mas achei essa uma solução provisória funcional

2022-10-06 23:14 UTC, mblucs commented on src/pages/Cadastro.tsx
> +      {signUpSuccess !== null &&
estou aberto a sugestões!
essa foi uma solução provisória pra retornar se o cadastro foi realizado ou n

2022-10-06 23:14 UTC, mblucs commented on src/pages/Cadastro.tsx
> +              <InputLabel htmlFor="login">Matrícula</InputLabel>
botei como login pq no final oq ta realmente validando o usuário é o login, não a matricula

2022-10-06 23:14 UTC, mblucs commented on src/pages/Cadastro.tsx
> +                type="number"
conforme modelo do back

2022-10-06 23:26 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +  semestre_pgcomp: number | string;
oxe, estranho hein

2022-10-06 23:26 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +  const [signUpSuccess, setSignUpSuccess] = React.useState<boolean | null>(
viu o outro coment q deixei la embaixo?

2022-10-06 23:27 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +      .post("/alunos", signUpData)
pega o exemplo da pag de mostrar todos os editais

2022-10-06 23:28 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +    window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
ta funcional, porem ta sincrona, né?

a req é assíncrona 

dá p botar isso dentro um `finally`

se n der p entender, fala no zap q eu mando áudio explicando rs (preguiça)

2022-10-07 00:03 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +      {signUpSuccess !== null &&
Não tenho sugestões KKKKKKK
Vou pensar

2022-10-07 00:04 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +              <InputLabel htmlFor="login">Matrícula</InputLabel>
mas o "login" no sentido de validação é algo pro back se preocupar, certo?

o login pode ser matricula (aluno), siape (prof), string (root)

p mim nesse caso especifico (cadastro de aluno no sistema), parece fzr mais sentido "matricula"

2022-10-07 00:05 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +  semestre_pgcomp: number | string;
sugiro ver c o pessoal do back

2022-10-07 00:19 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +    window.scrollTo({ top: 0, left: 0, behavior: "smooth" });
mandei no zap

2022-10-07 00:19 UTC, BeatrizCerqueira commented on src/pages/Cadastro.tsx
> +      {signUpSuccess !== null &&
mandei no zap

2022-10-07 04:55 UTC, BeatrizCerqueira requested changes

2022-10-07 04:55 UTC, BeatrizCerqueira commented on src/Components/BtnSubmitLoading.tsx
> +//   export default function EditalItem({ edital, onClick }: IProps) {
```suggestion

```

2022-10-07 04:55 UTC, BeatrizCerqueira commented on src/Components/BtnSubmitLoading.tsx
> +  form: string;
Acho form-id mais intuitivo

2022-10-07 04:55 UTC, BeatrizCerqueira commented on src/pages/Cadastro/Cadastro.tsx
> +      login: signUpData.matricula,
Isso pode dar merda, eu acho

Pq o setState é assíncrono, lembra? Pode ser que ele bote no login um valor antigo de matrícula caso seja a matrícula q esteja mudando

Provisoriamente, vc pode botar um `if` pra tratar a matrícula separadamente... caso a alteração seja na matrícula muda login e matrícula, caso contrário segue o fluxo padrão

2022-10-07 04:55 UTC, BeatrizCerqueira commented on src/pages/Cadastro/Cadastro.tsx
> +    // console.log(signUpData);
:eyes:

2022-10-07 04:55 UTC, BeatrizCerqueira commented on src/pages/Cadastro/Cadastro.tsx
> +                label="matricula"
```suggestion
                label="Matrícula"
```

2022-10-07 04:55 UTC, BeatrizCerqueira commented on src/pages/Cadastro/Cadastro.tsx
> +        <BtnSubmitLoading
Cadê meu card actions?????

Destrua meu padrão naaaaao :sob:

2022-10-07 13:28 UTC, mblucs commented on src/pages/Cadastro/Cadastro.tsx
> +        <BtnSubmitLoading
ta dentro do componente!!!! e ficou até melhor pq padroniza tamanho (eu achei)

2022-10-07 17:05 UTC, BeatrizCerqueira commented on src/pages/Cadastro/Cadastro.tsx
> +        <BtnSubmitLoading
Mas é q todos os outros cards têm, né? Na minha opinião ajuda a padronizar os espaçamentos. Aí vc n precisaria daquele `pb: 4` lá em cima por ex, né? Mas ok ok fzr oq

2022-10-07 17:07 UTC, BeatrizCerqueira approved these changes

2022-10-07 17:10 UTC, merged