POSG79 funcionalidade header
mate85-equipe03/frontend pull request #45
Opened 2022-10-03 20:37 UTC by mblucs

2022-10-06 22:19 UTC, BeatrizCerqueira requested changes

2022-10-06 22:19 UTC, BeatrizCerqueira commented on src/Components/Header.tsx
> +              <Button variant="text" disableRipple sx={{ mr: 1 }}>
Cadê a ação do botão, bonito? kkkkk

2022-10-07 00:50 UTC, BeatrizCerqueira approved these changes

2022-10-07 00:51 UTC, mblucs commented on src/Components/Header.tsx
> +  const isCadastro = useLocation().pathname === "/cadastro";
nhe

2022-10-07 00:52 UTC, mblucs commented on src/themes/DefaultTheme.tsx
> +            textTransform: "initial",
usei em mais de 2 botões preferi colocar como padrão.
enquanto n teve nenhum botão com uppercase

2022-10-07 00:53 UTC, merged